-- Modelo SQL equivalente ao banco criado automaticamente pelo Spring/JPA.
-- Use este arquivo se o professor pedir a estrutura relacional documentada.
CREATE TABLE usuarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(80) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  senha VARCHAR(255) NOT NULL,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE redacoes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id BIGINT NOT NULL,
  titulo VARCHAR(160) NOT NULL,
  tema VARCHAR(300) NOT NULL,
  texto CLOB NOT NULL,
  nota INTEGER CHECK (nota BETWEEN 0 AND 1000),
  feedback CLOB,
  status VARCHAR(30) NOT NULL DEFAULT 'CORRIGIDA',
  criada_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_redacao_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);

CREATE INDEX idx_redacoes_usuario_data ON redacoes(usuario_id, criada_em DESC);
